version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: ./server
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/analytics"
    ports:
      - '3000:3000'
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node dist/main.js"

volumes:
  pgdata:
